### ISSUE TITLE
Call to undefined method zfhassaan\genlytics\facades\AnalyticsFacade::runReports()

### ISSUE THREAD

**Issue by khawala** [zfhassaan/genlytics#7]
i got this error when i try to run the report i already publish evrythings
Call to undefined method zfhassaan\genlytics\facades\AnalyticsFacade::runReports() 

this is my code
   $analytics = new Genlytics();
        $period = ['start_date' => '2017-01-01','end_date' => 'today'];
          $dimensions = ['name' => 'yearMonth']; 
    $metrics = ['name' => 'pageviews']; 
         $result = $analytics->runReports($period, $dimensions, $metrics);

**Comment by zfhassaan** [comment]
@khawala sorry for the late fix, the query on GA4 is changed from pageViews to "screenPageViews" You can test the new package with the following code: 

```php
            $analytics = new Genlytics();
            $period = ['start_date' => '2017-01-01','end_date' => 'today'];
            $dimensions = ['name' => 'yearMonth'];
            $metrics = ['name' => 'screenPageViews'];
            $result = $analytics->runReports($period, $dimensions, $metrics);
```

I fixed some other minor issues for the package. Will update the docs too. Thanks.

**Comment by zfhassaan** [comment]
Query Explorer : https://ga-dev-tools.google/ga4/query-explorer/

If it's showing data on this explorer it'll work on this package.
